services:
  evaluate-layoutlmv3:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: vcsdoc-evaluate-layoutlmv3
    volumes:
      - ./:/app
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ~/.paddleocr:/root/.paddleocr
    gpus: all
    command:
      - python
      - -m
      - src.services.evaluate_layoutlmv3
      - --config
      - configs/evaluate_layoutlmv3.json

  evaluate-donut:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: vcsdoc-evaluate-donut
    volumes:
      - ./:/app
      - ~/.cache/huggingface:/root/.cache/huggingface
    gpus: all
    command:
      - python
      - -m
      - src.services.evaluate_donut
      - --config
      - configs/evaluate_donut.json
